#!/bin/bash

#PBS -ASTF007
#PBS -lwalltime=00:30:00,nodes=800

source $MODULESHOME/init/bash
module load cudatoolkit
module switch cray-mpich2 cray-mpich2/5.6.1
module load vampirtrace

cd /tmp/work/atj/my_vampir
export VT_PFORM_GDIR=/tmp/work/atj/my_vampir/traces
cp /tmp/work/atj/sph.out .
export VT_FILTER_SPEC=/tmp/work/atj/my_vampir/filter

export VT_BUFFER_SIZE=200M
export VT_MAX_FLUSHES=10

export VT_BINDIR=/tmp/work/atj/.vt/pgi/bin/

aprun -n 800 -d 16 ./sph.out
